const venuesData = [
    {
      venueName: "Sri Navodaya Function Hall",
      address: "Guntur Road, Sulthanabad, Tenali, Andhra Pradesh 522202",
      stars: "3.9",
      place: "Tenali",
      contactInfo: { phone: "9700275111" },
      capacity: 400,
      event_type: ["wedding", "engagement", "corporate", "conference"],
      event_location: "Tenali",
    },
    {
      venueName: "Goutham Grand Hotel",
      address:
        "D.No: 8-19-110, Railway Station Road, Morrispet, Tenali - 522202, Guntur(Dist), Andhra PradeshP",
      stars: "4",
      place: "Tenali",
      contactInfo: { phone: "7660000695", email: "reserv@gouthamhotels.com" },
      capacity: 1000,
      event_type: ["engagement", "wedding", "birthday", "corporate", "conference"],
      event_location: "Tenali",
    },
    {
      venueName: "Sasi Vedika",
      address:
        "6JRX+X3Q, Ganganamma Peta, Ramalingeswara Pet, Tenali, Andhra Pradesh 522201",
      stars: "3.9",
      place: "Tenali",
      contactInfo: { phone: "7093313344" },
      capacity: 200,
      event_type: ["birthday", "kitty", "conference"],
      event_location: "Tenali",
    },
    {
      venueName: "Chavas Grand Function Hall",
      address: "6JWJ+PX7, Sulthanabad, Tenali, Andhra Pradesh 522201",
      stars: "4.2",
      place: "Tenali",
      contactInfo: { phone: "9866554055", email: "info@chavasgrand.com" },
      capacity: 400,
      event_type: ["wedding", "engagement", "conference"],
      event_location: "Tenali",
    },
    {
      venueName: "Ratna Fortune Convention Hall",
      address: "Alapati Nagar, 32-8-4/c, Sulthanabad, Tenali, Andhra Pradesh 522202",
      stars: "4.2",
      place: "Tenali",
      contactInfo: { mobile: "8121212449" },
      capacity: 500,
      event_type: ["wedding", "engagement", "corporate", "conference"],
      event_location: "Tenali",
    },
    {
      venueName: "Sri Padmavathi Kalyana Mandapam",
      address: "Ponduranga Pet, Tenali, Andhra Pradesh 522201",
      stars: "4.2",
      place: "Tenali",
      contactInfo: { phone: "9959427496" },
      capacity: 300,
      event_type: ["wedding", "engagement"],
      event_location: "Tenali",
    },
    {
      venueName: "Biryanis and More",
      address: "Bose Rd, opp. Town Church, Ramalingeswara Pet, Tenali, Andhra Pradesh 522201",
      stars: "3.7",
      place: "Tenali",
      contactInfo: { phone: "9069041234", email: "info@biryanis.com" },
      capacity: 20,
      event_type: ["birthday"],
      event_location: "Tenali",
    },
    {
      venueName: "Grand Adithee Rooms and Banquets",
      address: "6MP2+5HQ, opp. Axis bank, Kothapet, Kothapeta, Tenali, Andhra Pradesh 522201",
      stars: "4.2",
      place: "Tenali",
      contactInfo: { phone: "7093313344" },
      capacity: 200,
      event_type: ["birthday", "kitty", "conference"],
      event_location: "Tenali",
    },
    {
      venueName: "Siddhartha Gardens & Convention Center",
      address: "4-18, 28/72, Ring Road, Chandramouli Nagar, Guntur, Andhra Pradesh 522006",
      stars: "4.5",
      place: "Guntur",
      contactInfo: { phone: "9866599955" },
      capacity: 1000,
      event_type: ["wedding", "corporate", "conference", "engagement"],
      event_location: "Guntur",
    },
    {
      venueName: "B Convention Center",
      address: "Near Andhra Muslim College, Guntur, Andhra Pradesh 522003",
      stars: "4.5",
      place: "Guntur",
      contactInfo: { phone: "9246485282" },
      capacity: 330,
      event_type: ["wedding", "engagement", "conference"],
      event_location: "Guntur",
    },
    {
      venueName: "The Orchid Banquet Hall",
      address: "Brodipet, Guntur, Andhra Pradesh 522002",
      stars: "4.2",
      place: "Guntur",
      contactInfo: { phone: "Not Available" },
      capacity: 120,
      event_type: ["birthday", "kitty party"],
      event_location: "Guntur",
    },
    {
      venueName: "Blue Leaf Restaurant Party Hall",
      address: "Lakshmipuram, Guntur, Andhra Pradesh 522007",
      stars: "4.0",
      place: "Guntur",
      contactInfo: { phone: "Not Available" },
      capacity: 80,
      event_type: ["birthday", "kitty party"],
      event_location: "Guntur",
    },
    {
      venueName: "Hotel Grand Nagarjuna Banquet Hall",
      address: "Arundelpet, Guntur, Andhra Pradesh 522002",
      stars: "4.1",
      place: "Guntur",
      contactInfo: { phone: "Not Available" },
      capacity: 150,
      event_type: ["corporate", "conference", "birthday"],
      event_location: "Guntur",
    },
    {
      venueName: "PVR Grand Function Hall",
      address: "Sampath Nagar, Guntur, Andhra Pradesh 522004",
      stars: "4.3",
      place: "Guntur",
      contactInfo: { phone: "Not Available" },
      capacity: 500,
      event_type: ["wedding", "engagement", "conference"],
      event_location: "Guntur",
    },
    {
      venueName: "Lotus Party Hall",
      address: "Krishna Nagar, Guntur, Andhra Pradesh 522006",
      stars: "4.0",
      place: "Guntur",
      contactInfo: { phone: "Not Available" },
      capacity: 60,
      event_type: ["birthday", "kitty party"],
      event_location: "Guntur",
    },
    {
      venueName: "Club One Party Lounge",
      address: "Lakshmipuram, Guntur, Andhra Pradesh 522007",
      stars: "4.2",
      place: "Guntur",
      contactInfo: { phone: "Not Available" },
      capacity: 50,
      event_type: ["birthday", "kitty party"],
      event_location: "Guntur",
    },
    {
      venueName: "Fortune Murali Park",
      address: "40-1-28, MG Road, Labbipet, Vijayawada, Andhra Pradesh",
      stars: "4.5",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 400,
      event_type: ["wedding", "corporate", "conference", "engagement"],
      event_location: "Vijayawada",
    },
    {
      venueName: "Ayla Event Space & Gardens",
      address: "Kanuru, Vijayawada, Andhra Pradesh",
      stars: "3.9",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 600,
      event_type: ["wedding", "corporate", "conference", "birthday"],
      event_location: "Vijayawada",
    },
    {
      venueName: "Hotel Southern Grand",
      address: "29-6-9, Eluru Rd, Governorpet, Vijayawada, Andhra Pradesh",
      stars: "4.0",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 200,
      event_type: ["birthday", "kitty party", "corporate", "conference"],
      event_location: "Vijayawada",
    },
    {
      venueName: "The Gateway Hotel MG Road",
      address: "39-1-63, MG Road, Labbipet, Vijayawada, Andhra Pradesh",
      stars: "4.4",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 500,
      event_type: ["wedding", "corporate", "conference", "engagement"],
      event_location: "Vijayawada",
    },
    {
      venueName: "Ilapuram Hotel",
      address: "40-1-73, Benz Circle, MG Road, Vijayawada, Andhra Pradesh",
      stars: "4.1",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 300,
      event_type: ["wedding", "corporate", "conference", "birthday"],
      event_location: "Vijayawada",
    },
    {
      venueName: "Hotel Marg Krishnaaya",
      address: "40-1-47, MG Road, Labbipet, Vijayawada, Andhra Pradesh",
      stars: "4.0",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 250,
      event_type: ["wedding", "corporate", "conference","engagement"],
      event_location: "Vijayawada",
    },
    {
      venueName: "Hotel Aira",
      address: "40-1-100, MG Road, Labbipet, Vijayawada, Andhra Pradesh",
      stars: "4.2",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 150,
      event_type: ["corporate", "conference"],
      event_location: "Vijayawada",
    },
    {
      venueName: "DV Manor",
      address: "40-1-47, MG Road, Labbipet, Vijayawada, Andhra Pradesh",
      stars: "4.3",
      place: "Vijayawada",
      contactInfo: { phone: "Not Available" },
      capacity: 350,
      event_type: ["wedding", "corporate", "conference", "birthday"],
      event_location: "Vijayawada",
    }
  ];
  
  module.exports = venuesData;

  